const GREETINGS = [
    // --- Sweet & Simple ---
    "Aaj ka din tumhara hai, enjoy karo ✨",
    "Bas aise hi hasti raho hamesha 🌸",
    "Tumhara vibe aaj alag hi hai ☀️",
    "Good vibes only, Prachi 🌟",
    "Chalo kuch acha karte hain aaj 🎯",
    "Tum thoda sa magic ho 💫",
    "Keep shining, Prachi 🌟",
    "Aaj tumhara din bohot acha jaayega, trust me ☕",
    "Tumhara smile dekh ke sab ka din ban jaata hai 😊",
    "Aaj kuch naya try karo, tum kar sakti ho 💪",
    "Itni strong ho tum, pata bhi hai tumhe? 🦋",
    "Just checking in — tum theek ho na? 🤗",
    "Prachi, tum sabse alag ho — best wali alag ✨",
    "Thoda rest bhi le lena aaj 🌙",
    "Tumhara laugh is literally contagious 😂",
    "Aaj chai pi ke chill karo thoda ☕",
    "Tum bohot brave ho, yaad rakho 🔥",
    "Prachi, tumpe trust hai — full 💯",

    // --- Motivation ---
    "Tum jo chaho kar sakti ho, seriously 💪",
    "Haar mat maano, bohot close ho tum 🎯",
    "Tumhara time aayega, patience rakho ⏳",
    "Ek din sab sort ho jaayega, tab tak lado 🔥",
    "Tum already bohot dur aa chuki ho ✨",
    "Jab tak haar na maano, haar nahi hoti 🏆",
    "Prachi, tum kisi se kam nahi 👑",
    "Tumhara potential bohot hai, dikhana abhi baaki hai 🌟",
    "Chhota step bhi step hai, keep going 🚶‍♀️",
    "Tum padh lo thoda, phir saath mein chill karenge 📚",
    "NEET crack hoga, tension mat lo 🧬",
    "Ek ek din matter karta hai, aaj bhi 🗓️",
    "Hard work ka result aayega, wait karo 🌈",
    "Tum ne bohot mushkil waqt dekha hai, ab achha aayega 🌸",
    "Consistency is key, aur tum consistent ho 🔑",
    "Focus mode ON karo, tum kar sakti ho 🎧",
    "Bohot kam log itne dedicated hote hain jitni tum ho 👏",
    "Aaj thoda sa padh lo, kal ka pressure kam hoga 📖",
    "Tum apne aap pe believe karo 💯",
    "Tumhari mehnat rang laayegi, I know it 🌈",

    // --- Caring & Soft ---
    "Khaana kha liya? Mat bhoolna 🍛",
    "Paani pi lo, dehydration se concentration kam hota hai 💧",
    "Neend poori lena aaj, health pehle 😴",
    "Agar kuch bura laga ho toh bata dena 🤗",
    "Main sun raha hoon, bolo kya hua 👂",
    "Tumhara health > everything else, yaad rakho 🏥",
    "Thak gayi ho toh rest lo, koi rush nahi 🛋️",
    "Aaj stress lene ka nahi, chill karo 😎",
    "Phone rakho aur thoda walk kar lo 🚶‍♀️",
    "Tumhari aankhein mat strain karo, break lo 👀",
    "Bohot garmi hai aaj, hydrated raho 🥤",
    "Tum kabhi akeli nahi ho, yaad rakhna 💗",
    "Koi bhi problem ho, hum saath mein solve karenge 🤝",
    "Agar rona aaye toh rok ke mat rakhna, it's okay 🥺",
    "Tum perfect nahi ho, aur that's perfectly fine 💕",
    "Apne aap ko mat judge karo itna 🌸",

    // --- Appreciation ---
    "Tumhe pata hai tum kitni talented ho? 🎨",
    "Tum bohot acchi listener ho 👂",
    "Tumhare ideas hamesha unique hote hain 💡",
    "Tum jo bhi karti ho, dedication dikhti hai 🔥",
    "Tum mein patience hai bohot, seriously 😤",
    "Tum bohot caring ho, even when you don't realize 💗",
    "Tumhara sense of humor underrated hai 😂",
    "Tum detail oriented ho, that's rare ✨",
    "Bohot kam log itne genuine hain jitni tum ho 🌸",
    "Tumhara confidence bohot achha hai 👑",
    "Tum simple cheezon ko special bana deti ho 💫",
    "Tum har situation handle kar leti ho, respect 💪",
    "Tumhe khud ki value pata honi chahiye 💎",
    "Tumhara positivity contagious hai ☀️",
    "Tum bohot mature ho apni age ke liye 🤝",
    "Tum mein leadership quality hai, for real 🏅",
    "Tum sabko comfortable feel karati ho 🤗",
    "Tumhari ek baat jo mujhe genuinely impress karti hai — consistency 🔥",
    "Tum curious ho, ye quality bahut rare hai 🧠",
    "Tumhari memory sharpen hai, kuch bhi bhoolti nahi 📌",
    "Tum logical aur emotional dono ho — perfect balance ⚖️",
    "Tumhara kisi bhi topic pe opinion interesting hota hai 💡",
    "Tum jab kuch explain karti ho toh samajh aata hai seedha 🎯",
    "Bohot sochi samjhi baatein karti ho tum 🌿",

    // --- Confidence Boosters ---
    "Tum kuch bhi pehn lo, sab suit karta hai 👗",
    "Tum apni photo mat delete karo, achhi hai 📸",
    "Comparison mat karo kisi se, tum unique ho 💎",
    "Tum mein confidence already hai, sirf dikhana shuru karo 👑",
    "Tumhari ek alag hi identity hai, preserve karo usse 🌸",
    "Baaki log kya sochte hain — irrelevant. Tum kya sochti ho matter karta hai 🧠",
    "Tum average nahi ho, kabhi na socho aisa 🌟",
    "Tumhari strengths tumhare weaknesses se zyada hain 💪",
    "Log tum se seekhte hain, chahe dikhate na ho 🌱",
    "Khud pe doubt karna off karo — tum capable ho 🔐",

    // --- Support during tough times ---
    "Agar aaj mushkil hai, toh kal better hoga 🌈",
    "Agar rona aaye toh roko mat 🫂",
    "Har problem ka solution hai, dhundenge saath mein 🔍",
    "Tum akeli nahi ho is mein, promise 🤝",
    "Aaj bura gaya? Kal naya din hai 🌅",
    "Strong hona zaroori nahi har waqt, it's okay 💕",
    "Tumhe khud pe doubt hai? Mujhe nahi 💯",
    "Kabhi kabhi break lena bhi zaroori hai 🛑",
    "Tum bohot kuch handle karti ho, respect 🙏",
    "Agar overwhelmed feel ho rahi ho toh ek ek cheez karo 📝",
    "Comparison mat karo, tumhara journey alag hai 🛤️",
    "Tum mein itna potential hai jo abhi dikhna baaki hai 🌱",
    "Bad days don't mean bad life, yaad rakho 💫",
    "Koi bhi tumhe judge kare, ignore karo — tum amazing ho ✨",
    "Stress lene se kuch nahi hota, ek cheez pe focus karo 😌",
    "Tum deserve karti ho sabse achha 🏆",
    "Apne aap ke liye proud feel karo, tum bohot far aa chuki ho 👏",
    "Ek din ye sab struggles memories banenge 📸",

    // --- Playful & Fun ---
    "Aaj kya kiya pura din? Batao na 🤔",
    "Chalo ek game khelte hain 🎮",
    "Mujhe ek joke sunana hai tumhe, yaad dilana 😂",
    "Aaj ka mood kya hai tumhara? 🎭",
    "Tum kitna soti ho yaar 😴",
    "Bohot baat karna hai tumse aaj 💬",
    "Tum kabhi boring nahi lagti mujhe 💯",
    "Mujhe tumhara opinion chahiye ek cheez pe 🤔",
    "Chalo kuch naya try karte hain 🆕",
    "Tumhara typing speed dekh ke darr lagta hai 😂",
    "Tum hamesha sahi hoti ho, irritating hai par sach hai 😅",
    "Mujhe tumhari sass sunne mein maza aata hai 🤣",
    "Tum jab sleepy hoti ho, bohot funny lagti ho 😴😂",
    "Tum stubborn ho, but achhi wali stubborn 🐢",
    "Mujhe tumhara rant sunna achha lagta hai 🗣️",
    "Mere saath fight karke bhi baat karti ho, respect 🤝",
    "Tumhe jaldi ready hona seekhna chahiye 🕐",
    "Tum meri sabse honest critic ho, that's why I trust you 💯",

    // --- Evening / Night ---
    "Goodnight Prachi, sweet dreams 🌙",
    "Aaj ka din kaisa raha? Sab batao 📝",
    "Raat ko overthink mat karna, so jao 💤",
    "Kal phir se fresh start, aaj rest karo 🌸",
    "Aaj bohot productive din tha, proud of you 👏",
    "Late night cravings? 🍕",
    "Phone rakho aur so jao ab 📵",
    "Ek last chiz padh ke so jao, achha feel hoga 📖",
    "Night, Prachi. Tum best ho 🌟",
    "Aaj bohot thak gayi hogi, rest lo 🛌",
    "Kal milte hain phir se ☕",
    "Raat ko overthink band karo, padhi hui cheezein process hoti hain sapne mein 🧠",

    // --- Morning ---
    "Good morning sunshine ☀️",
    "Uth jao Prachi, bohot so liya 😤",
    "Subah ki chai pi lo pehle ☕",
    "Aaj ka plan kya hai? 📋",
    "Fresh start, fresh day — chalo shuru karte hain 🌅",
    "Aaj bohot productive hona hai, ready? 💪",
    "Rise and shine, Prachi 🌸",
    "Breakfast kar lena pehle 🥞",
    "Aaj mausam acha hai, enjoy karo ☁️",
    "Morning walk kar lo thoda 🚶‍♀️",
    "Pehle paani piyo, phir phone chalao 💧",
    "Aaj ka ek goal set karo 🎯",
    "Coffee ya chai? ☕",

    // --- Days / Occasions ---
    "Weekend hai, chill karo 🎉",
    "Monday hai, himmat rakho 💪",
    "Mid-week feel ho raha hai? Bus thoda aur 💪",
    "Friday vibes = best vibes 🎊",
    "Sunday funday, kya plan hai? 🌈",
    "Rainy day = chai + padhai 🌧️☕",
    "Garmi mein nimbu paani pi lo 🧊",
    "Sardi hai, warm raho 🧣",

    // --- Deep / Thoughtful ---
    "Tumhara perspective hamesha naya hota hai 💡",
    "Kabhi kabhi silence mein bhi bahut kuch sochte ho tum 🤫",
    "Tumhara trust sabse badi cheez hai 🏆",
    "Kuch log genuinely good hote hain — tum unme ho 🌸",
    "Tumhara dedication dekh ke lagta hai sab possible hai ✨",

    // --- Study related ---
    "Padhai ho gayi aaj ki? 📚",
    "Ek chapter aur kar lo, phir break 📖",
    "Mock test de lo aaj ek 🧪",
    "Revision kar lo is week ka 🔄",
    "Bohot padha aaj? Proud of you 👏",
    "Formula yaad karne mein help chahiye? 🧮",
    "Previous year papers dekh lo thode 📋",
    "Concentration kam ho rahi hai? 5 min break lo 🧘‍♀️",
    "Tum NEET mein top karogi, mujhe pata hai 🏆",
    "Biology padh lo thodi, wo strong hai tumhara 🧬",
    "Physics mein doubt hai? Discuss karte hain 🔬",
    "Chemistry toh confident area hai tumhara 🧪",
    "Time table follow kar rahi ho? 📅",
    "Distraction hatao, focus karo 🎯",
    "Smart study > long study, yaad rakho 🧠",
    "Tumhe explain karna achha aata hai, teaching try karo 👩‍🏫",
    "Aaj ka target complete hua? ✅",
    "Padhai ke baad reward do khud ko 🎁",
    "Ek topic select karo aur sirf usse karo aaj 🎯",
    "Notes organized hain? Revision easy hoti hai organized notes se 📋",
    "Flashcards try karo revision ke liye 🗂️",
    "Pomodoro technique try karo — 25 min on, 5 min break ⏱️",
    "Aaj jo padha uska summary likho — retention improve hogi ✍️",

    // --- Food / Life ---
    "Khaana time pe khao, dimaag tab kaam karta hai 🍛",
    "Chalo pizza order karte hain 🍕",
    "Ice cream kabhi kabhi zaroori hai 🍦",
    "Bohot bhookh lagi hai, tum bhi kha lo 🍔",
    "Late night mein kuch healthy kha lo 🥗",
    "Tumhe biryani pasand hai ya pulao? Important question 🍚",
    "Aaj ghar ka khaana khao, bahar ka mat 🏠",
    "Maggi comfort food hai, agreed ☕",

    // --- Random Positive ---
    "Kabhi socha hai tum kitni dur tak ja sakti ho? 🚀",
    "Tumhari ek habit hai jo mujhe pasand hai — genuine hona 🌿",
    "Tum kisi bhi room mein alag notice hoti ho ✨",
    "Tumhare baare mein ek interesting fact — tum genuinely intelligent ho 🧠",
    "Tum dono empathetic aur practical ho — rare combination 🤝",
    "Tumhare andar wo spark hai jo dikhta hai 🔥",
    "Tum apna best version ban rahi ho — slowly but surely 🌱",
    "Tumhari growth dekh ke genuinely proud feel hota hai 👏",
    "Ek din sab log tumhara naam izzat se lenge, wait karo 🌟",
    "Tumhara koi bhi decision sochke kiya hua hota hai, impulsive nahi 🧩",

    // --- Life Advice ---
    "Toxic log se door raho, energy waste mat karo 🚫",
    "Boundaries rakhna seekho, bohot important hai 🧱",
    "Sabko khush karna zaroori nahi, pehle khud ko 💎",
    "Tumhari mental health sabse pehle, baaki sab baad mein 🧘",
    "Galti hona normal hai, seekhna zaroori hai 📝",
    "Kisi ki baat se hurt ho toh bol do, andar mat rakho 💬",
    "Time management kar lo thoda, sab fit ho jaayega 🕐",
    "Ek hobby bana lo apni, mind fresh rahega 🎨",
    "Social media se break lo kabhi kabhi 📵",
    "Self care mat bhoolo, importance hai uski 🛁",
    "Ek routine banao, consistency aayegi 📋",
    "Logon ki opinions temporary hain, tumhara growth permanent 🌱",
    "Ek journal rakho, thoughts clear hote hain 📓",
    "Tumhara gut feeling sahi hota hai mostly, suno usse 🤫",
    "Quality > quantity, har cheez mein 💯",
    "Tumhara circle chhota par loyal rakho 🤝",
    "Complain karne se achha solution nikaalo 🔧",
    "Life mein patience bohot kaam aata hai 🕊️",
    "Kabhi kabhi na bolna bhi zaroori hai — learn to decline gracefully 🙅‍♀️",
    "Comparison trap mein mat pado, apna path banao 🛤️",
    "Health invest hai future ke liye, abhi se sochna shuru karo 🏥",
    "Ek cheez daily improve karo — compounding works 📈",

    // --- Nostalgia ---
    "Purani photos dekhne ka mann hai 📸",
    "Time kitna jaldi nikal gaya, laga hi nahi 🕐",
    "Kabhi kabhi sochta hoon kaise yahan tak pahunche 🛤️",
    "Woh pehle wale din bhi kya din the 🌸",

    // --- Gratitude / Genuine Connection ---
    "Thank you for being honest with me, always 🙏",
    "Tum mujhe samajhti ho, that means a lot 🤗",
    "Tumhara support genuinely matter karta hai 💪",
    "Tumhare saath baat karna refreshing hota hai 🌿",
    "Tum patient rehti ho, that's a real quality 🙏",
    "Tumhara time dena — uski value pata hai mujhe 💗",
    "Thanks for being you, Prachi 💕",
    "Tumhare jaisi dost rare hoti hai 🌸",
    "Tumse baat karne ke baad mood acha ho jaata hai 😊",
    "Tum genuine ho — aur aajkal ye bohot rare hai 🌟",

    // --- Silly Questions ---
    "Agar superpower milti toh kya leti? 🦸‍♀️",
    "Ek island pe ek cheez le ja sakti toh kya? 🏝️",
    "Time travel mein kahan jaogi? Past ya future? ⏰",
    "Pizza pe pineapple — haan ya na? 🍍",
    "Last song jo loop pe suna? 🎵",
    "Winter ya summer — choose one forever ❄️☀️",
    "Cat person ya dog person? Honest answer 🐱🐕",
    "Tumhara dream vacation destination? ✈️",
    "Favourite season kaunsa hai? 🍂",
    "Tumhara comfort food kya hai? 🍕",
    "Morning person ya night owl? 🌅🦉",
    "Mountains ya beach? 🏔️🏖️",
    "Tumhara go-to emoji kaunsa hai? 🤔",
    "Ek cheez jo tum daily use karti ho aur uske bina nahi ho sakti? 📱",
    "Agar ek subject roz padhna padta zindagi bhar, kaunsa? 📚",
    "Tea ya coffee — aaj wala honest answer 🍵",
    "Agar unlimited budget milta ek din ke liye, kya karti? 💸",
    "Koi ek skill jo seekhni hai future mein? 🔧",
    "Favorite childhood memory ek word mein? 🧸",
    "Agar apna ek quality describe karo — kya bologe? 🤔",

    // --- Music / Movies ---
    "Ek song recommend karo mujhe 🎵",
    "Tumhe konsi movie dekhni hai? 🎬",
    "Aaj purane gaane sunte hain 📻",
    "Tumhara taste in music achha hai actually 🎶",
    "Mujhe tumhara fav song ka naam batao 🎤",
    "Late night lo-fi chalao aur padho 🎧📚",
    "Ek Bollywood crush scene recommend karo 🍿",
    "Tumhara all-time fav movie? 🎬",

    // --- Everyday Moments ---
    "Auto mein baith ke gaana suno, trip lagega 🎧",
    "Chai ke saath parle-G = underrated combo ☕",
    "Terrace pe baith ke stars dekhte hain 🌌",
    "Chalo ek walk pe chalte hain, bas yunhi 🚶",
    "Photo albums dekhte hain purane wale 📷",
    "Chalo ek painting banaate hain saath mein 🎨",
    "Library jaake books browse karte hain 📖",
    "Raat ko terrace pe saath mein ginti karenge stars 🌠",
    "Early morning walk karna hai, 5 baje wala 🌅",
    "Chalo market se golgappe khaate hain 🤤",
    "Ek plant grow karte hain saath mein 🌿",
    "Board game night plan karte hain 🎲",

    // --- Diary Specific ---
    "Diary likh do aaj ki 📖",
    "Aaj kuch positive likho, irrespective of the day 🌸",
    "Secret letter option use karo kisi ek cheez ke liye 💌",
    "Aaj se roz ek entry — consistency practice hai 🤝",
    "Ye tumhara space hai, freely likho 🌿",

    // --- Weekend Plans ---
    "Saturday hai, kuch plan karo warna regreat hoga 📺",
    "Sunday ko kuch nahi karna hai, bas aaram 🛋️",
    "Weekend pe ek naya recipe try karte hain 🍳",
    "Lazy Sunday = best Sunday 😴",
    "Shopping karna hai kya? 🛍️",
    "Aaj adventure karne ka man hai 🏔️",

    // --- Genuine Prachi-specific Appreciation ---
    "Tum jo mehnat karti ho wo dikhi nahi deti, par result mein hoti hai 🔥",
    "Tumhari curiosity ek strength hai, nurture karo isko 🌱",
    "Tum ek problem ko multiple angles se dekhti ho — that's smart 🧩",
    "Tumhare andar discipline hai, usse underestimate mat karo 📌",
    "Tum careful ho — sochke bolti ho, impulsive nahi 🕊️",
    "Tumhari genuine care dikhti hai, sabko feel hoti hai 💗",
    "Tum empathy aur logic dono ke saath sochti ho 🤝",
    "Tumhara kisi bhi cheez mein quality dhundhna — bohot achha hai 💎",
    "Tum apni mistakes se genuinely seekhti ho 📚",
    "Tumhare andar guts hai — kuch bhi bol deti ho jo sach ho 🎯",
    "Tumhara optimism kabhi kabhi mujhe bhi bohot kaam aata hai ☀️",
    "Tum bohot organized sochti ho — rare at your age 📋",
    "Tumhare plans sensible hote hain, random nahi 🗺️",
    "Tum kisi bhi cheez mein genuinely interested hoti ho toh wo dikhta hai 🌟",
    "Tumhara aesthetic sense genuinely achha hai 🎨",
    "Tum kisi ke feelings ko seriously lete ho — that's not common 🌸",

    // --- Final Batch ---
    "Aaj kuch creative karo, mind ko free karo 🎨",
    "Tumhari hasi genuinely infectious hai 🎶",
    "Chalo ek positive cheez likho aaj ke baare mein 📝",
    "Aaj ka din tumhare naam, make it count 🌟",
    "Prachi, tum jo ho — as a person — genuinely good ho 🌍",
    "Tum whatever you do, do it with full honesty — that's your thing 💯",
    "Keep going, results aane wale hain 🚀",
    "Proud of how far you've come, honestly 🏆",
    "Tum ek better version banti ja rahi ho, din b din ✨",
    "Respect for the grind, seriously 🔥",
]

export default GREETINGS
